version: '2.3'

services:

  back-end:
    image: back-end:latest
    restart: "on-failure"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O -  http://$$(hostname -i):8080/actuator/health | grep -q '^{\"status\":\"UP\"'"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 10s

  front-end:
    image: front-end:latest
    restart: "on-failure"
    healthcheck:
      test: ["CMD-SHELL", "service nginx status || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 10s
    depends_on:
      back-end:
        condition: service_healthy

  proxy:
    image: nginx:1.13.0
    restart: "on-failure"
    ports:
      - "5000:5000"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    healthcheck:
      test: ["CMD-SHELL", "service nginx status || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 10s
    depends_on:
      back-end:
        condition: service_healthy
      front-end:
        condition: service_healthy

  regression-test:
    image: regression-test:latest
    depends_on:
      proxy:
        condition: service_healthy

  selenium:
    image: selenium/standalone-chrome-debug:3.14
    ports:
      - "9515:4444"
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://$$(hostname -i):4444/wd/hub/status | grep -q 'Server is running'"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 10s
    depends_on:
      proxy:
        condition: service_healthy

  ui-test:
    image: ui-test:latest
    environment:
      - DRIVER_URL=http://selenium:4444/wd/hub
      - FE_URL=http://proxy:5000
    depends_on:
      selenium:
        condition: service_healthy