version: '2.3'

services:

  back-end:
    image: back-end:latest
    restart: "on-failure"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O -  http://$$(hostname -i):8080/actuator/health | grep -q '^{\"status\":\"UP\"'"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 10s

  front-end:
    image: front-end:latest
    restart: "on-failure"
    healthcheck:
      test: ["CMD-SHELL", "service nginx status || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 10s
    depends_on:
      back-end:
        condition: service_healthy

  proxy:
    image: nginx:1.13.0
    restart: "on-failure"
    ports:
      - "5000:5000"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    healthcheck:
      test: ["CMD-SHELL", "service nginx status || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 10s
    depends_on:
      back-end:
        condition: service_healthy
      front-end:
        condition: service_healthy